[package]
name = "aptos-voting-smart-contract"
version = "1.0.0"
authors = []

[addresses]
MyModule = "0x53a476e0017d801d2d77c5267f2b03fc78572664a417e8ae837b977ddc40a6fb"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "devnet"
subdir = "aptos-framework"

[dev-dependencies]
